include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = ColdWhitePrefs
ColdWhitePrefs_FILES = CWRootListController.m
ColdWhitePrefs_FRAMEWORKS = UIKit
ColdWhitePrefs_PRIVATE_FRAMEWORKS = Preferences
ColdWhitePrefs_INSTALL_PATH = /Library/PreferenceBundles
ColdWhitePrefs_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/bundle.mk
