include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = ColdWhitePrefs
ColdWhitePrefs_FILES = CWRootListController.m
ColdWhitePrefs_FRAMEWORKS = UIKit
ColdWhitePrefs_LDFLAGS = -undefined dynamic_lookup
ColdWhitePrefs_INSTALL_PATH = /Library/PreferenceBundles
ColdWhitePrefs_CFLAGS = -fobjc-arc
ColdWhitePrefs_INFO_PLIST = Info.plist
include $(THEOS_MAKE_PATH)/bundle.mk
